"""baseline

Revision ID: a7263be2ad89
Revises: 
Create Date: 2026-07-03 14:41:15.787691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7263be2ad89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.String(length=2000), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_table('client_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=32), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('registered_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'ip', name='uq_client_tenant_ip')
    )
    op.create_index(op.f('ix_client_entries_group_id'), 'client_entries', ['group_id'], unique=False)
    op.create_index(op.f('ix_client_entries_ip'), 'client_entries', ['ip'], unique=False)
    op.create_index(op.f('ix_client_entries_tenant_id'), 'client_entries', ['tenant_id'], unique=False)
    op.create_table('dhcp_ha_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('this_server_name', sa.String(length=128), nullable=False),
    sa.Column('this_server_url', sa.String(length=255), nullable=False),
    sa.Column('peer_name', sa.String(length=128), nullable=False),
    sa.Column('peer_url', sa.String(length=255), nullable=False),
    sa.Column('peer_role', sa.String(length=32), nullable=False),
    sa.Column('max_unacked_clients', sa.Integer(), nullable=True),
    sa.Column('max_ack_delay_ms', sa.Integer(), nullable=True),
    sa.Column('heartbeat_delay_ms', sa.Integer(), nullable=True),
    sa.Column('retry_wait_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('feeds',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('license', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('from_catalog', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('last_version', sa.String(length=64), nullable=True),
    sa.Column('last_etag', sa.String(length=255), nullable=True),
    sa.Column('last_domain_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('qname', sa.String(length=255), nullable=False),
    sa.Column('qtype', sa.String(length=16), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('matched_rule', sa.String(length=32), nullable=True),
    sa.Column('matched_category', sa.String(length=64), nullable=True),
    sa.Column('matched_feed_id', sa.String(length=64), nullable=True),
    sa.Column('response_code', sa.String(length=16), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.Column('latency_us', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_events_client_ip'), 'query_events', ['client_ip'], unique=False)
    op.create_index(op.f('ix_query_events_group_id'), 'query_events', ['group_id'], unique=False)
    op.create_index(op.f('ix_query_events_occurred_at'), 'query_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_query_events_seq'), 'query_events', ['seq'], unique=True)
    op.create_index(op.f('ix_query_events_tenant_id'), 'query_events', ['tenant_id'], unique=False)
    op.create_table('siem_webhooks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('secret_encrypted', sa.String(length=1024), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('flush_interval_s', sa.Integer(), nullable=False),
    sa.Column('filter_decision', sa.String(length=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_delivered_seq', sa.BigInteger(), nullable=False),
    sa.Column('last_delivered_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=2000), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_siem_webhooks_tenant_id'), 'siem_webhooks', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('upstream_pools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('strategy', sa.String(length=30), nullable=False),
    sa.Column('health_check_interval_s', sa.Integer(), nullable=False),
    sa.Column('health_check_timeout_ms', sa.Integer(), nullable=False),
    sa.Column('health_check_query', sa.String(length=255), nullable=False),
    sa.Column('health_check_type', sa.String(length=10), nullable=False),
    sa.Column('unhealthy_threshold', sa.Integer(), nullable=False),
    sa.Column('healthy_threshold', sa.Integer(), nullable=False),
    sa.Column('min_healthy_members', sa.Integer(), nullable=False),
    sa.Column('fallback_pool_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fallback_pool_id'], ['upstream_pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upstream_resolvers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('tls_hostname', sa.String(length=255), nullable=True),
    sa.Column('tls_pin_sha256', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('doh_path', sa.String(length=255), nullable=False),
    sa.Column('doh_method', sa.String(length=10), nullable=False),
    sa.Column('dnssec_validation', sa.String(length=20), nullable=False),
    sa.Column('qname_minimization', sa.Boolean(), nullable=False),
    sa.Column('edns_client_subnet', sa.Boolean(), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('connect_timeout_ms', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upstream_tenant_policies',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('require_encrypted', sa.Boolean(), nullable=False),
    sa.Column('dnssec_validation', sa.String(length=20), nullable=False),
    sa.Column('qname_minimization', sa.Boolean(), nullable=False),
    sa.Column('blocked_response_type', sa.String(length=20), nullable=False),
    sa.Column('min_ttl_s', sa.Integer(), nullable=False),
    sa.Column('max_ttl_s', sa.Integer(), nullable=False),
    sa.Column('negative_ttl_s', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dhcp_scopes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('subnet', sa.String(length=50), nullable=False),
    sa.Column('range_start', sa.String(length=45), nullable=False),
    sa.Column('range_end', sa.String(length=45), nullable=False),
    sa.Column('router_ip', sa.String(length=45), nullable=True),
    sa.Column('dns_servers', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('ntp_server', sa.String(length=45), nullable=True),
    sa.Column('domain_name', sa.String(length=255), nullable=True),
    sa.Column('interface', sa.String(length=64), nullable=True),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('lease_time_s', sa.Integer(), nullable=False),
    sa.Column('max_lease_time_s', sa.Integer(), nullable=False),
    sa.Column('renew_time_s', sa.Integer(), nullable=True),
    sa.Column('rebind_time_s', sa.Integer(), nullable=True),
    sa.Column('ddns_enabled', sa.Boolean(), nullable=False),
    sa.Column('ddns_zone_id', sa.String(length=36), nullable=True),
    sa.Column('ddns_ttl_s', sa.Integer(), nullable=False),
    sa.Column('pxe_next_server', sa.String(length=45), nullable=True),
    sa.Column('pxe_boot_filename', sa.String(length=255), nullable=True),
    sa.Column('kea_subnet_id', sa.Integer(), nullable=True),
    sa.Column('last_pushed_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'subnet', name='uq_dhcp_scope_subnet')
    )
    op.create_index(op.f('ix_dhcp_scopes_tenant_id'), 'dhcp_scopes', ['tenant_id'], unique=False)
    op.create_table('dhcp_scopes6',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('subnet', sa.String(length=50), nullable=False),
    sa.Column('pool_start', sa.String(length=45), nullable=False),
    sa.Column('pool_end', sa.String(length=45), nullable=False),
    sa.Column('pd_prefix', sa.String(length=50), nullable=True),
    sa.Column('pd_prefix_len', sa.Integer(), nullable=True),
    sa.Column('dns_servers', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=True),
    sa.Column('interface', sa.String(length=64), nullable=True),
    sa.Column('preferred_lifetime_s', sa.Integer(), nullable=False),
    sa.Column('valid_lifetime_s', sa.Integer(), nullable=False),
    sa.Column('renew_time_s', sa.Integer(), nullable=True),
    sa.Column('rebind_time_s', sa.Integer(), nullable=True),
    sa.Column('ddns_enabled', sa.Boolean(), nullable=False),
    sa.Column('ddns_zone_id', sa.String(length=36), nullable=True),
    sa.Column('ddns_ttl_s', sa.Integer(), nullable=False),
    sa.Column('kea_subnet_id', sa.Integer(), nullable=True),
    sa.Column('last_pushed_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'subnet', name='uq_dhcp_scope6_subnet')
    )
    op.create_index(op.f('ix_dhcp_scopes6_tenant_id'), 'dhcp_scopes6', ['tenant_id'], unique=False)
    op.create_table('dns_zones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('zone_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('ttl_default', sa.Integer(), nullable=False),
    sa.Column('forwarder', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name')
    )
    op.create_table('groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vpn_subnet', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_group_tenant_name')
    )
    op.create_table('upstream_pool_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pool_id', sa.String(length=36), nullable=False),
    sa.Column('resolver_id', sa.String(length=36), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['upstream_pools.id'], ),
    sa.ForeignKeyConstraint(['resolver_id'], ['upstream_resolvers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'resolver_id', name='uq_pool_member')
    )
    op.create_table('upstream_routes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('match_value', sa.String(length=255), nullable=True),
    sa.Column('pool_id', sa.String(length=36), nullable=False),
    sa.Column('nxdomain_ttl_override', sa.Integer(), nullable=True),
    sa.Column('require_dnssec', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['upstream_pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upstream_routes_tenant_id'), 'upstream_routes', ['tenant_id'], unique=False)
    op.create_table('dhcp_relay_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=False),
    sa.Column('relay_ip', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('circuit_id_hex', sa.String(length=255), nullable=True),
    sa.Column('remote_id_hex', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['scope_id'], ['dhcp_scopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dhcp_static_leases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('next_server', sa.String(length=45), nullable=True),
    sa.Column('boot_filename', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['dhcp_scopes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_id', 'ip_address', name='uq_dhcp_static_ip')
    )
    op.create_index(op.f('ix_dhcp_static_leases_scope_id'), 'dhcp_static_leases', ['scope_id'], unique=False)
    op.create_index(op.f('ix_dhcp_static_leases_tenant_id'), 'dhcp_static_leases', ['tenant_id'], unique=False)
    op.create_table('dhcp_static_leases6',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('duid', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['dhcp_scopes6.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dhcp_static_leases6_tenant_id'), 'dhcp_static_leases6', ['tenant_id'], unique=False)
    op.create_table('dns_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('record_type', sa.String(length=10), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('data', sa.String(length=1024), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['dns_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('on_load_failure', sa.String(length=20), nullable=False),
    sa.Column('bundle_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id')
    )
    op.create_table('dhcp_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=True),
    sa.Column('static_lease_id', sa.String(length=36), nullable=True),
    sa.Column('option_code', sa.Integer(), nullable=False),
    sa.Column('option_space', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('always_send', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['dhcp_scopes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['static_lease_id'], ['dhcp_static_leases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_category_toggles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'category_id', name='uq_policy_category')
    )
    op.create_table('policy_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy_overrides')
    op.drop_table('policy_category_toggles')
    op.drop_table('dhcp_options')
    op.drop_table('policies')
    op.drop_table('dns_records')
    op.drop_index(op.f('ix_dhcp_static_leases6_tenant_id'), table_name='dhcp_static_leases6')
    op.drop_table('dhcp_static_leases6')
    op.drop_index(op.f('ix_dhcp_static_leases_tenant_id'), table_name='dhcp_static_leases')
    op.drop_index(op.f('ix_dhcp_static_leases_scope_id'), table_name='dhcp_static_leases')
    op.drop_table('dhcp_static_leases')
    op.drop_table('dhcp_relay_configs')
    op.drop_index(op.f('ix_upstream_routes_tenant_id'), table_name='upstream_routes')
    op.drop_table('upstream_routes')
    op.drop_table('upstream_pool_members')
    op.drop_table('groups')
    op.drop_table('dns_zones')
    op.drop_index(op.f('ix_dhcp_scopes6_tenant_id'), table_name='dhcp_scopes6')
    op.drop_table('dhcp_scopes6')
    op.drop_index(op.f('ix_dhcp_scopes_tenant_id'), table_name='dhcp_scopes')
    op.drop_table('dhcp_scopes')
    op.drop_table('users')
    op.drop_table('upstream_tenant_policies')
    op.drop_table('upstream_resolvers')
    op.drop_table('upstream_pools')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_siem_webhooks_tenant_id'), table_name='siem_webhooks')
    op.drop_table('siem_webhooks')
    op.drop_index(op.f('ix_query_events_tenant_id'), table_name='query_events')
    op.drop_index(op.f('ix_query_events_seq'), table_name='query_events')
    op.drop_index(op.f('ix_query_events_occurred_at'), table_name='query_events')
    op.drop_index(op.f('ix_query_events_group_id'), table_name='query_events')
    op.drop_index(op.f('ix_query_events_client_ip'), table_name='query_events')
    op.drop_table('query_events')
    op.drop_table('feeds')
    op.drop_table('dhcp_ha_configs')
    op.drop_index(op.f('ix_client_entries_tenant_id'), table_name='client_entries')
    op.drop_index(op.f('ix_client_entries_ip'), table_name='client_entries')
    op.drop_index(op.f('ix_client_entries_group_id'), table_name='client_entries')
    op.drop_table('client_entries')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
