apiVersion: v1
kind: Service
metadata:
  name: {{ include "mantis-dns.fullname" . }}-control
  labels:
    {{- include "mantis-dns.labels" . | nindent 4 }}
    app.kubernetes.io/component: control
spec:
  type: {{ .Values.control.service.type }}
  ports:
    - port: {{ .Values.control.port }}
      targetPort: {{ .Values.control.port }}
  selector:
    app.kubernetes.io/name: {{ include "mantis-dns.fullname" . }}
    app.kubernetes.io/component: control
