#!/usr/bin/env node
/*
 * Copyright (C) 2026 Blue Networks srl <support+github@bluenetworks.it>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * Regenerates src/api/schema.ts from the control plane's live OpenAPI schema.
 *
 * The schema is dumped by services/control/scripts/dump_openapi.py, which
 * builds it from the FastAPI app object directly — no running server,
 * Postgres, or network call needed (just `mantis_control` importable, i.e.
 * `pip install -e .` done in an active venv).
 *
 *   node scripts/gen-api.mjs          regenerates src/api/schema.ts in place.
 *   node scripts/gen-api.mjs --check  exits 1 if the committed file is stale
 *     instead of writing — used by CI so an API change without a matching
 *     schema.ts regen fails the build instead of shipping a UI typed against
 *     a stale contract.
 */

import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import openapiTS, { astToString } from "openapi-typescript";

const __dirname = dirname(fileURLToPath(import.meta.url));
const uiRoot = join(__dirname, "..");
const controlDir = join(uiRoot, "..", "..", "services", "control");
const schemaPath = join(uiRoot, "src", "api", "schema.ts");
const checkMode = process.argv.includes("--check");

const LICENSE_HEADER = `/*
 * Copyright (C) 2026 Blue Networks srl <support+github@bluenetworks.it>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

`;

const python = process.platform === "win32" ? "python" : "python3";
const dump = spawnSync(python, ["scripts/dump_openapi.py"], {
  cwd: controlDir,
  encoding: "utf-8",
  maxBuffer: 16 * 1024 * 1024,
});
if (dump.status !== 0) {
  if (dump.stderr) {
    process.stderr.write(dump.stderr);
  }
  if (dump.error) {
    console.error(dump.error.message);
  }
  console.error(
    "\nFailed to dump the OpenAPI schema from the control plane. Is " +
      "mantis_control installed in an active venv (`pip install -e '.[dev]'` " +
      "in services/control)?"
  );
  process.exit(1);
}

const schema = JSON.parse(dump.stdout);
const ast = await openapiTS(schema);
const generated = LICENSE_HEADER + astToString(ast);

if (checkMode) {
  const current = readFileSync(schemaPath, "utf-8");
  if (current !== generated) {
    console.error(
      "src/api/schema.ts is out of date with the control plane's OpenAPI schema.\n" +
        "Run `npm run gen:api` (with the control-plane venv active) and commit the result."
    );
    process.exit(1);
  }
  console.log("src/api/schema.ts is up to date.");
} else {
  writeFileSync(schemaPath, generated);
  console.log("Wrote src/api/schema.ts");
}
